import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Notification from "@/components/General/Notification";
import Navbar from "@/components/Navigation/Navbar";
import Footer from "@/components/General/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* ==================Always put components inside body========================== */}
      <body className={inter.className}>
        <Notification />
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
